name: custom one
description: description

inputs:
  input_one:
    description: input one
    required: false
    default: one 1

outputs:
  output_one:
    description: some output
    value: ${{ steps.out.outputs.my_output }}

runs:
  using: composite
  steps:
    - name: one
      run: echo one
      shell: bash
    - run: pwd
      shell: bash
    - run: echo my_output=dope! >> $GITHUB_OUTPUT
      id: out
      shell: bash