name: all

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/all.yaml
  workflow_dispatch:
  workflow_call:
    inputs:
      required:
        description: one
        required: true
        type: string
      default:
        description: default
        required: true
        default: default
        type: string
      optional:
        description: optional
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  basic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /tmp
        shell: sh
    steps:
      - run: pwd
      - run: pwd
        working-directory: /bin
    outputs:
      out_one: uno

  variables:
    runs-on: ubuntu-latest
    needs: basic
    env:
      env_one: one
    steps:
      - run: echo env_two=two > $GITHUB_ENV
      - run: |
          echo $env_one
          echo $env_two
      - run: |
          echo ${{ env.env_one }}
          echo ${{ needs.basic.outputs.out_one }}
          echo ${{ github.repository }}
          
          if [[ "${{ inputs.required }}" != "" ]]; then
            echo workflow call
          else
            echo not workflow call
          fi

  parallel:
    runs-on: ubuntu-latest
    steps:
      - run: echo parallel 1

  fail-and-proceed:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: echo fail; exit 1
        continue-on-error: true
      - run: echo still running
      - run: echo sleeping; sleep 65s
        timeout-minutes: 1
        continue-on-error: true
      - run: echo still running 2
      - run: echo early exit; exit 1
      - run: echo not gonna run

  end:
    runs-on: ubuntu-latest
    steps:
      - run: echo end