name: build

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Build and Test
        run: |
          npm install
          npm run test -- --watch false --browsers ChromeHeadless
          npm run build
      - name: Setup dynamic variables
        run: |
          echo ${{ github.repository }} | awk -F/ '{print "REPOSITORY_NAME="$2}' >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/${{ env.REPOSITORY_NAME }}-${{ inputs.environment }}
          aws-region: us-east-2
      - run: |
          aws sts get-caller-identity
          aws s3 sync --sse AES256 ./dist/ng-ui/browser/ s3://${{ env.REPOSITORY_NAME }}-${{ inputs.environment }}-${{ vars.AWS_ACCOUNT }}